---
# vars file for Docker
docker_compose_download_url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
docker_ce_version: 5:26.0.0-1~ubuntu.24.04~noble
docker_ce_cli_version:  5:26.0.0-1~ubuntu.24.04~noble
docker_apt_repository_url: https://download.docker.com/linux/ubuntu
docker_gpg_apt_key_download_url: "{{ docker_apt_repository_url }}/gpg"
